README.md
REQUIRE
deps/build.jl
docs/make.jl
docs/src/dsp.md
docs/src/fft.md
docs/src/index.md

This will also test whether Travis and AppVeyor are happy with the build setup.

WIP: Package polishing

---

.gitignore
deps/build.jl

Work in progress, simultaneously testing this and the new sudo-less bindeps branch

[WIP] Fix apt-get installation stuff

---

src/FFTW.jl

Might as well since this is 0.6 only

use `@__DIR__`

---

src/FFTW.jl

https://github.com/JuliaMath/FFTW.jl/pull/6#discussion_r120142738

Use relative path for the deps include

---

src/FFTW.jl

Revert "Use relative path for the deps include"

---

src/FFTW.jl
src/fft.jl

This was a to-do for this day, when FFTW is in its own package

Move thread initialization to module __init__

---

deps/build.jl
src/FFTW.jl
src/fft.jl

@staticfloat could you update your commit to keep the Homebrew use on macOS? Or is that problematic? (Can just `rebase -i HEAD~2` and fixup, then force push to this branch. I would do it but I want to preserve authorship.)

Elliot's fix

---

src/fft.jl
test/runtests.jl

Ref #25 and https://github.com/JuliaLang/julia/issues/23063

Temporarily mark the 2D brfft inference test as broken

---

REQUIRE
src/package.jl
test/runtests.jl

Reexport symbols from AbstractFFTs

---

src/fft.jl

Fix uses of now-lazy adjoint

---

README.md

Basically copied wholesale from Steven G. Johnson's comments in https://github.com/JuliaMath/FFTW.jl/pull/41#discussion_r141930786.

Better explanation of GPL consequences

---

src/fft.jl
test/runtests.jl

fix mistypo

---

.travis.yml
appveyor.yml
deps/build.jl
src/FFTW.jl

Upgrade to 0.7/1.0

---

README.md

Ref https://github.com/JuliaLang/julia/issues/30812

Friendlier homepage with usage instructions

---

.cirrus.yml

Add Cirrus script to test the package on FreeBSD

---

test/runtests.jl

Should fix #100.
@giordano, if you can try this locally on ARM that would be helpful.

fix alignment check

---

.drone.yml

Someone will probably need to enable Drone CI for this repository.  Results of the tests in my fork: https://cloud.drone.io/giordano/FFTW.jl/12/

Add Drone CI script

---

Project.toml

To include the `@static` fix from #138.

Bump version to 1.2.1

---

src/fft.jl

I was wondering if there's any reason for the `region` field of the FFTWPlan types to be `Any`.
This PR sets `region` to a concrete (parametric) type. Tests pass, at least on my machine with Julia 1.3.0-rc3.
Feel free to ignore this if there's something I'm missing.

Use parametric type for `region` field

---

test/runtests.jl

I thought it's nice to see the progress of the tests as they go and more easily have an idea where they fail

Group tests with `@testset`

---

Project.toml

Any objections to a new release?

Version 1.3.2

---

Project.toml
src/FFTW.jl
src/providers.jl
test/Project.toml
test/runtests.jl

Simplify `test/Project.toml` and remove redundant deps in `Project.toml`

---

.drone.jsonnet
.drone.yml

Ref: https://discourse.julialang.org/t/testing-julia-packages-on-x86-64-alpine-linux-with-drone-ci/57313

Run CI with Drone also on Alpine Linux

---

Project.toml

cc @KristofferC, @andreasnoack

Bump version to 1.4.0

---

Project.toml

This should include the recent improvements in type-stability
cc @stevengj

Bump version to v1.5.1

---

Project.toml

see #263
Type parameters added/modified in #259 and #253

bump to 1.6 since new type params were added

---

.github/workflows/CI.yml

This makes it easier to understand if a failure is due to nightly being buggy

Test on the latest stable release

---

Project.toml

Bumping for #249 etc., cc @gaurav-arya 
See also https://github.com/FluxML/Zygote.jl/pull/1437
Once this is merged, will ping JuliaRegistrator to tag the release.

Bump to 1.8
