JuliaMath/FFTW.jl

deps/build.jl

Given
```
julia> WinRPM.search("fft")
WinRPM Package Set:
1. fftw3-debug (mingw64) - Debug information for package mingw64-fftw3
2. fftw3-debugsource (mingw64) - Debug sources for package mingw64-fftw3
3. fftw3-devel (mingw64) - Include Files and Libraries mandatory for Development
4. libfftw3-3 (mingw64) - Discrete Fourier Transform (DFT) C Subroutine Library
```
it seems that WinRPM might be expecting the package to be called `libfftw3-3`. So let's try that on AppVeyor and see what happens.

Correct the RPM package name on Windows

---

src/fft.jl

Stop using ANY

---

.travis.yml
REQUIRE
deps/build.jl

Use the FFTW binaries from fftw-builder

---

README.md

Fixes #39.
Note: CI skipped, remove from commit message when merging.

Mention GPL in the README

---

deps/build.jl
deps/build_fftw.jl

@EthanAnderes, could you clone this branch and try it out? In particular we want to make sure that the file `~/.julia/v0.7/FFTW/deps/deps.jl` exists and says MKL in it, and that you get the expected performance boost.
If all is well, fixes #40.

Use MKL for FFTs if Julia's BLAS is MKL

---

REQUIRE
deps/build.jl
deps/build_fftw.jl
src/FFTW.jl
src/dct.jl
src/fft.jl
test/runtests.jl

Closes #56 and #58.
This includes a number of deprecation fixes, and bumps the minimum Julia version to be in sync with AbstractFFTs so that we can just rewrite the LinearAlgebra stuff entirely.

Grabbag of fixes for 0.7

---

docs/src/fft.md

The documentation of AbstractFFTs has been moved to https://juliamath.github.io/AbstractFFTs.jl/stable/api/, however the documention of FFTW had not been updated. This commit updates that link. Fixes #101

Fixed link to AbstractFFTs in docs

---

.gitignore
Project.toml
docs/src/index.md

This pins AbstractFFTs and BinaryProvider to 0.5.x. Since FFTW reexports AbstractFFTs, breaking changes in AbstractFFTs propagates downstream via FFTW, as FFTW previously set only a lower bound on AbstractFFTs. In preparation for a release, this also sets the package version to 1.1.0.
This also has a separate commit that updates the documentation to be relevant to the 1.0 era.

Restrict dependency version bounds

---

Project.toml
src/FFTW.jl

This adds a missing compatibility entry for FFTW_jll and simplifies the checks for `Threads.@spawn` existing.

Minor cleanup for Julia 1.3

---

.travis.yml
deps/build.jl
src/FFTW.jl

#127 adds travis to windows and tests MKL builds, which are failing.
On master, appveyor was missing MKL tests, so this just wasn't being tested

Fix windows MKL & add windows to travis (windows MKL wasn't being tested)

---

src/FFTW.jl

This line looks suspicious to me — seems like this needs to be a runtime check, not in `@static if`.

nthreads check should be outside of static if

---

src/FFTW.jl

Defaulting to multi-threaded FFTW was causing too many slowdowns in code that was calling FFTW in parallel from multiple threads (where the right thing is to use the serial FFTW, especially given Julia's current thread-spawning overhead).
Closes #121.  Closes JuliaDSP/DSP.jl#339.

don't set nthreads > 1 by default

---

src/FFTW.jl
src/fft.jl

Should fix #141.  Closes #157.

use Julia ReentrantLock rather than fftw_make_planner_threadsafe

---

src/fft.jl

uses a spintest to avoid task switches in finalizers

---

Project.toml
src/fft.jl
test/runtests.jl

Companion PR to https://github.com/JuliaMath/AbstractFFTs.jl/pull/48

Improve inference, bump AbstractFFTs [compat]

---

.github/workflows/CI.yml
Project.toml

This should finally fix the failures on Windows with Julia nightly.

Allow installing MKL_jll 2021

---

src/fft.jl

This fixes the following problem:
```julia
julia> docat(v) = [v...]
docat (generic function with 1 method)
julia> code_typed(docat, (UnitRange{Int},))
1-element Vector{Any}:
CodeInfo(
1 ─ %1 = Core._apply_iterate(Base.iterate, Base.vect, v)::Vector{_A} where _A
└──      return %1
) => Vector{_A} where _A
julia> code_typed(docat, (Vector{Int},))
1-element Vector{Any}:
CodeInfo(
1 ─ %1 = Core._apply_iterate(Base.iterate, Base.vect, v)::Union{Vector{Any}, Vector{Int64}}
└──      return %1
) => Union{Vector{Any}, Vector{Int64}}
```
Essentially, because `region...` is implemented via the parser,
it relies on the call `vect(args...)` and the risk is that `args`
might be empty, which causes it to return `Vector{Any}`.

Improve inferrability of [region...]

---

src/dct.jl

This PR fixes a typo in the `dct!` / `idct!` doc strings.

Small doc fixes

---

src/fft.jl

The interpolated variable `libfftw3` will evaluate at precompile time to the path to the local directory of the fftw library. This means that if you e.g. build a sysimage using FFTW and move it somewhere else that sysimage will not work properly. Instead, use `:libfftw3` which evaluates to the variable `libfftw3` which is set during runtime. This is likely what was originally intended.
cc @staticfloat @giordano @andreasnoack

prevent to library from being serialized at precompile time

---

README.md

The README of the repository still refers to the old provider interface based on the environment variable `JULIA_FFTW_PROVIDER` which has no effect anymore.

Update README to account for set_provider!

---

Project.toml
src/fft.jl

This PR adds a safepoint in the `maybe_destroy_plan` spin lock to permit forward progress in that spin lock.
Without it, the spin lock blocks forward progress and can ultimately deadlock the program.
This was implemented according to [this observation](https://github.com/JuliaMath/FFTW.jl/issues/163#issuecomment-852444447).
I have tested this locally by running the minimum reproducible example; I can't get the program to deadlock any more.
I would like to write an automated test for this, but I can't think of one that would be reliable and run in a timely manner. My best method of testing this is running the minimal example code locally repeatedly and seeing if the program deadlocks.
Fixes #163.

Add a safepoint in the maybe_destroy_plan spin lock

---

src/FFTW.jl
src/fft.jl
src/providers.jl
test/runtests.jl

Because we need to know the FFTW vendor pretty early (at precompile
time to generate code, and at runtime) we need to load the path during
build (which bakes it into the precompile image), however we need to
update that path on next load within `__init__()` in case we're a part
of PackageCompiler and we need to be able to move things around without
requiring a recompile.  So we change all accesses of `libfftw3{,f}` to
be through a `Ref{String}()`, then update that ref within `__init__()`.
In the future, accesses of `FFTW_jll.libfftw3` will be through a
function, rather than a direct variable access, and we'll be able to get
these things for free, but that's still a ways down the line.

Make FFTW relocatable for PackageCompiler

---

src/FFTW.jl

`libfftw3` is used inside `fftw_init_threads()` so we need to update the paths first.
cc @staticfloat

make FFTW relocatable, take 2

---

src/precompile.jl

Failing to even compile the package is way too harsh if just one of the precompile statements fail. cc @timholy

remove asserts from precompile

---

src/fft.jl

Rename the output variable to make the result exactly inferred, and reduce temporary allocations.

inference + allocation in `fix_kinds`

---

src/fft.jl
test/runtests.jl

Instead of storing the value of `kinds` as a type parameter in `r2r` transforms, we may store it as a struct field instead, as this improves type-stability. This doesn't rely on the value being constant propagated.
This is a somewhat hacky approach to improve type-inference in `plan_r2r`, in the case where `kinds` and `region` are compile-time constants. This is a common use case, so, for example, the following is type-stable after this:
```julia
julia> @inferred (() -> FFTW.plan_r2r(rand(4), FFTW.REDFT10))()
FFTW r2r REDFT10 plan for 4-element array of Float64
(redft10e-r2hc-4
(rdft-r2hc-direct-r2c-4 "r2cf_4"))
```
The idea is that, in this case, the second type parameter of `r2rFFTWPlan` may be evaluated at compile time instead of a runtime call converting a `Vector` to a `Tuple`. This …

Improve type inference in `plan_r2r`

---

src/dct.jl

This parameterizes a `DCTPlan` for better type inference. With https://github.com/JuliaMath/FFTW.jl/pull/253, this should make a `DCTPlan` type-stable.

improve type inference in DCTPlan

---

Project.toml
src/fft.jl

This removes the `fix_kinds` method that evaluates to a `Tuple`. This was introduced in https://github.com/JuliaMath/FFTW.jl/pull/253 as a constant-propagation hack, but it's unnecessary now, given that the value is stored as a field rather than as a type-parameter. Having the method uniformly return a `Vector{Int32}` will firstly reduce unnecessary compilation, and secondly make the type parameters more predictable. The result has to be materialized in any case to create the plan, so this doesn't add to allocations.

remove tuple specialization of fix_kinds

---

Project.toml
src/fft.jl
test/runtests.jl

This reduces some unnecessary allocations in `dims_howmany`. This may be reduced further  by using `StaticArrays`, but that's a separate discussion as it'll increase the load time.
On master
```julia
julia> X = rand(100, 100);
julia> @btime FFTW.dims_howmany($X, $X, $(collect(size(X))), 1)
689.000 ns (21 allocations: 1.59 KiB)
([100; 1; 1;;], [100; 100; 100;;])
```
This PR
Updated after https://github.com/JuliaMath/FFTW.jl/pull/269/commits/e15a9b8c8576a714f95d70cf32edf093c0b647a1
```julia
julia> @btime FFTW.dims_howmany($X, $X, size($X), 1);
73.707 ns (2 allocations: 160 bytes)
```

reduce allocations in dims_howmany

---

Project.toml
src/dct.jl
src/fft.jl
test/Project.toml
test/runtests.jl

Supports the new `AbstractFFTs.AdjointStyle` trait. ~This is a draft PR because https://github.com/JuliaMath/AbstractFFTs.jl/pull/78 and https://github.com/JuliaMath/AbstractFFTs.jl/pull/109 are not merged yet, which this PR relies on.~

Support new AbstractFFTs.AdjointStyle trait for FFT and DCT plans

---

Project.toml

This is what's causing https://github.com/SciML/NonlinearSolve.jl/issues/316. There must be a better way than versioning this every year?

Allow MKL_jll v2024

---

.github/workflows/CompatHelper.yml

Ref #283 
By default, CompatHelper does not make PRs to add or update `[compat]` entries for JLL packages.
However, if you want CompatHelper PRs for JLL packages, you can opt-into this behavior by setting `include_jll = true`.

CompatHelper: make PRs to bump JLL compat entries

---

.ci/macos_mkl_2023.jl
.github/workflows/CI.yml

In MKL 2024, Intel dropped support for macOS.

CI: for the macOS CI jobs with the MKL provider, force MKL_jll 2023 to be installed

---

.github/workflows/CI.yml

Some of the CI tests can stochastically take much longer than the expected runtime (around 3min), so this PR bumps the timeout period to avoid spurious CI failures

Increase CI timeout length

---

.github/workflows/CI.yml

Enabling Apple Silicon is a bit messy because of the cross product of all platforms. It's good to be able to test it though, and happy to improve the script if anyone has suggestions for simplification.
Is it useful to run all the tests on Julia nightly? I feel we can save CI time by removing nightly.

Update CI.yml for Apple Silicon

---

.github/workflows/CI.yml

We have the codecov token set up correctly, but this is still causing CI to fail. Don't gate PRs being green on codecov.

Do not fail if codecov fails

---

src/fft.jl

fix bug in plan_r2r! for num_threads != nothing

---

src/fft.jl

This makes the following example compile with `--trim`:
```julia
using FFTW
Base.@ccallable function main() :: Cint
v = fft([0; 1; 2; 1])
for elem in v
println(Core.stdout, elem)
end
return 0
end
```
```
$ ./fftw
4.0 + 0.0im
-2.0 + 0.0im
0.0 + 0.0im
-2.0 + 0.0im
```

Improve type inference

---

docs/Project.toml
docs/make.jl
docs/src/fft.md
docs/src/index.md
src/dct.jl
src/fft.jl

- **fix(docs): Update compat bound for Documenter and dev the package**
- **feat(docs): Add the DocumenterInterLinks package for external documentation links**
- **feat(docs): Use `@extref` for external references**
- **fix(docs): Add `warnonly=[:missing_docs]`**

Add external links to the documentation and update Documenter compat
